[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pump_v2_amm_again_again = "GuA9pdtCqntcxCCWr2W8WbD7YdN7RDCni1JrFbzibENg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/staccoverflow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
